// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKodcWKJlU22AV6SXNotbYYDyF0M9JGU',
    appId: '1:463647227413:web:5c99e01ef96d160472981c',
    messagingSenderId: '463647227413',
    projectId: 'smart-medicine-reminder-c6bfa',
    authDomain: 'smart-medicine-reminder-c6bfa.firebaseapp.com',
    storageBucket: 'smart-medicine-reminder-c6bfa.firebasestorage.app',
    measurementId: 'G-E18TM79YEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5YPv-RN28XO6-Q9mC419qjU9TI204AKo',
    appId: '1:463647227413:android:e0a8ac20caa7934672981c',
    messagingSenderId: '463647227413',
    projectId: 'smart-medicine-reminder-c6bfa',
    storageBucket: 'smart-medicine-reminder-c6bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmK0sy0pAtc3oR3nGxsx8bw61Y3GJ8KmE',
    appId: '1:463647227413:ios:7fcfc7bc2a06ddb972981c',
    messagingSenderId: '463647227413',
    projectId: 'smart-medicine-reminder-c6bfa',
    storageBucket: 'smart-medicine-reminder-c6bfa.firebasestorage.app',
    iosBundleId: 'com.example.mediremindapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmK0sy0pAtc3oR3nGxsx8bw61Y3GJ8KmE',
    appId: '1:463647227413:ios:7fcfc7bc2a06ddb972981c',
    messagingSenderId: '463647227413',
    projectId: 'smart-medicine-reminder-c6bfa',
    storageBucket: 'smart-medicine-reminder-c6bfa.firebasestorage.app',
    iosBundleId: 'com.example.mediremindapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJKodcWKJlU22AV6SXNotbYYDyF0M9JGU',
    appId: '1:463647227413:web:7457756c686bda4572981c',
    messagingSenderId: '463647227413',
    projectId: 'smart-medicine-reminder-c6bfa',
    authDomain: 'smart-medicine-reminder-c6bfa.firebaseapp.com',
    storageBucket: 'smart-medicine-reminder-c6bfa.firebasestorage.app',
    measurementId: 'G-H2HETYW6ZD',
  );
}
